import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import logo from '../public/assets/logoSn.png'
import Link from 'next/link'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
      <div className='container-nav'>
        <div className='logo'>  
        <Link href="/">
          <Image src={logo} />
        </Link>
        </div>
      
        <div>
            <nav>
              <Link href="/Termes">Termes et Conditions</Link>
              <Link href="/Politique">Politique de confidentialité</Link>
            </nav>
        </div>
      </div>
     
      <div>
        <div>
        <div></div>
        <div>
          <p>ghqdghqshgqdhjqed</p>
          <button> 
          <Link href="/Contact">Contact</Link>
          </button>
        </div>
        </div>
        <div> Copyright 2023Divin Diongo M. </div>
      </div>
      </main>
    </>
  )
}
